# Generated by Django 4.2.26 on 2025-11-25 11:33

import django.db.models.deletion
from django.db import migrations, models

import posthog.models.utils


class Migration(migrations.Migration):
    dependencies = [
        ("posthog", "0919_teammarketinganalyticsconfig__custom_source_mappings"),
    ]

    operations = [
        migrations.CreateModel(
            name="QuickFilter",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=posthog.models.utils.uuid7, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ("name", models.CharField(max_length=200)),
                ("property_name", models.CharField(max_length=500)),
                (
                    "type",
                    models.CharField(
                        choices=[("manual-options", "manual-options"), ("auto-discovery", "auto-discovery")],
                        default="manual-options",
                        max_length=50,
                    ),
                ),
                ("options", models.JSONField(default=list)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("team", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to="posthog.team")),
            ],
            options={
                "db_table": "posthog_quickfilter",
            },
        ),
        migrations.CreateModel(
            name="QuickFilterContextMembership",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=posthog.models.utils.uuid7, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ("context", models.CharField(max_length=100)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "quick_filter",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="context_memberships",
                        to="posthog.quickfilter",
                    ),
                ),
                ("team", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to="posthog.team")),
            ],
            options={
                "db_table": "posthog_quickfiltercontextmembership",
                "indexes": [
                    models.Index(fields=["team", "context"], name="posthog_qui_team_id_b5a88d_idx"),
                    models.Index(fields=["quick_filter", "context"], name="posthog_qui_quick_f_7c7b18_idx"),
                ],
            },
        ),
        migrations.AddConstraint(
            model_name="quickfiltercontextmembership",
            constraint=models.UniqueConstraint(
                fields=("team", "quick_filter", "context"), name="unique_filter_context_membership"
            ),
        ),
        migrations.AddIndex(
            model_name="quickfilter",
            index=models.Index(fields=["team"], name="posthog_qui_team_id_24fea4_idx"),
        ),
    ]
